config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'sessions#welcome'

  resources :users
  
  get '/login', to: "sessions#login"
  post '/login', to: "sessions#create"
  get '/home', to: "sessions#home"
  post  '/logout', to: 'sessions#destroy'

  resources :locations, only: [:show, :index] do
    resources :wonders, only: [:show, :index]
  end
  resources :wonders

end

#    <%= link_to "Click to reveal all seven wonders!", controller: :wonders, action: :index, method: :get %>

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :wonders

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    #Adds methods to set and authenticate against a BCrypt password
    validates :username, uniqueness: true, length: { minimum: 6 }
    validates :password, length: { minimum: 6 }

end

app/models/wonder.rb
class Wonder < ActiveRecord::Base
  belongs_to :location
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def show
    @location = Location.find(params[:id])
  end

  def index
    @locations = Location.all
    render :layout => "footer"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        @user = User.new
    end

    def login

    end
    
    def create
        @user = User.find_by(username: params[:username])
        #authenticates user credentials
        if @user && @user.authenticate(params[:password])
            #set session and redirect on success
            session[:user_id] = @user.id
            flash[:notice] = "You're in! :D"
            redirect_to '/home'
            
        else
            #returns to login page with error message
            message = "Try Again"
            redirect_to login_path, notice: message
        end

    end

    def home
        render :layout => "footer"
    end

    def welcome

    end

    def destroy
        session.delete :user_id
        flash[:notice] = "You have been logged out D:"
        redirect_to '/'
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.create(strong_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path         
        else
            render :new
        end
    end

    private

    def strong_params
        params.require(:user).permit(:username, :password)
    end

end

app/controllers/wonders_controller.rb
class WondersController < ApplicationController

  def index
    if params[:location_id]
      @wonders = Location.find(params[:location_id]).wonders
    else
      @wonders = Wonder.all
    end
    render :layout => "footer"
  end

  def show
    if params[:location_id]
      @wonder = Location.find(params[:location_id]).wonders.find(params[:id])
    else
      @wonder = Wonder.find(params[:id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dk</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/footer.html.erb
<!DOCTYPE html>
<html>
<head>
  <titleWonders of the World!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<br>

<footer>
    <%= button_to "Logout", :controller=> "sessions", :action=> "destroy"%>
    </footer>

<%= yield %>

</body>
</html>

app/views/locations/index.html.erb
<h1>Locations of seven wonders of the world!</h1>
<%= link_to "Click here to see all seven wonders of the world!", controller: :wonders, action: :index, method: :get %>
<ul>
<h2>Click on a city to reveal what wonder lies beneath</h2>
  <% @locations.each do |location| %>
    <li>
    <%= location.continent %>:
    <%= location.name %>,
    <%= link_to location.city, location_path(location) %></li>
  <% end %>
</ul>
<br>

app/views/locations/show.html.erb
<h1>Found in <%= @location.name %> lies..</h1>

<% @location.wonders.each do |wonder| %>
  <div>
  <h2><%= wonder.title %></h2>
  <ul>
  <h3>Discovered in <%= wonder.year_discovered %>..</h3><br>
  <%= wonder.description %>
  </ul>
  </div>
  <%= link_to "Return back", controller: :locations, action: :index, method: :get %>

<% end %>

app/views/users/new.html.erb
<h1>Sign Up Here</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being created:</h2>
    <ul>
      <% @user.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

<%= form_for(@user) do |f|%>
  <%= f.label :username%><br>
  <%= f.text_field :username%><br>
  <%= f.label :password%><br>
  <%= f.password_field :password%><br>
  
  <%= f.submit "Create account"%>

<% end %>

app/views/wonders/index.html.erb
<br>
<h1><b>Wonders of the world!</b></h1>

<% @wonders.each do |wonder| %>
  <div>
    <h2><%= wonder.title %></h2>
    <h3><%= link_to wonder.location.name, location_wonders_path(wonder.location) %></h3>
    <p><%= wonder.description %></p>
  </div>
<% end %>
<br>
<footer>
<%= link_to "Go back", controller: :locations, action: :index, method: :get %>
</footer>

app/views/wonders/show.html.erb
<h1><%= @wonder.title %></h1>
<p>by <%= link_to @wonder.location.name, location_path(@wonder.location) if @wonder.location %></p>
<p><%= @wonder.description %> </p>